# Generated by Django 3.2.8 on 2021-11-10 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='title of message.', max_length=120)),
                ('autor', models.CharField(help_text='autor of message.', max_length=120)),
            ],
        ),
    ]
