# Generated by Django 3.2.8 on 2021-11-10 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Libros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='numero_pag',
            field=models.IntegerField(default=1, help_text='Número de Páginas'),
            preserve_default=False,
        ),
    ]
