# Generated by Django 3.2.8 on 2021-11-17 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Libros', '0004_autos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Computadoras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(help_text='Marca del Computador', max_length=200)),
                ('serie', models.CharField(help_text='Serie', max_length=200)),
                ('precio', models.FloatField(help_text='Precio', max_length=200)),
            ],
        ),
    ]
