# Generated by Django 3.2.8 on 2021-11-17 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Libros', '0005_computadoras'),
    ]

    operations = [
        migrations.AddField(
            model_name='computadoras',
            name='modelo',
            field=models.CharField(default=1, help_text='Modelo', max_length=200),
            preserve_default=False,
        ),
    ]
